# Generated by Django 6.0.2 on 2026-02-21 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_profile_average_rating_profile_review_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='exchange_method',
            field=models.CharField(choices=[('in_person', 'Meet in Person'), ('gcash', 'GCash (or similar e-wallet)'), ('bank_transfer', 'Bank Transfer'), ('other', 'Other arrangement')], default='in_person', max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='notes',
            field=models.TextField(blank=True, help_text='Buyer notes about delivery/exchange (e.g., preferred meetup location)'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='seller_notes',
            field=models.TextField(blank=True, help_text='Seller confirmation notes (e.g., availability, location)'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending - Waiting for seller confirmation'), ('confirmed', 'Confirmed - Ready for exchange'), ('completed', 'Completed - Transaction finished'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
