# Generated by Django 6.0.2 on 2026-02-25 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_transaction_confirmed_at_transaction_exchange_method_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='forumpost',
            name='is_hidden',
            field=models.BooleanField(default=False, help_text='Moderator-hidden content'),
        ),
        migrations.AddField(
            model_name='forumpost',
            name='moderation_notes',
            field=models.TextField(blank=True, help_text='Internal moderator notes'),
        ),
        migrations.AddField(
            model_name='forumreply',
            name='is_hidden',
            field=models.BooleanField(default=False, help_text='Moderator-hidden content'),
        ),
        migrations.AddField(
            model_name='forumreply',
            name='moderation_notes',
            field=models.TextField(blank=True, help_text='Internal moderator notes'),
        ),
        migrations.AddField(
            model_name='message',
            name='is_hidden',
            field=models.BooleanField(default=False, help_text='Moderator-hidden content'),
        ),
        migrations.AddField(
            model_name='message',
            name='moderation_notes',
            field=models.TextField(blank=True, help_text='Internal moderator notes'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='admin_cancel_reason',
            field=models.TextField(blank=True, help_text='Documented reason for admin cancellation (audit trail)'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='admin_cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='admin_cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_cancelled_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaction',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Internal admin notes for dispute/fraud follow-up'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='flagged_for_review',
            field=models.BooleanField(default=False, help_text='Flagged by admin for follow-up'),
        ),
        migrations.CreateModel(
            name='ModerationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('hide_forum_post', 'Hide Forum Post'), ('restore_forum_post', 'Restore Forum Post'), ('hide_forum_reply', 'Hide Forum Reply'), ('restore_forum_reply', 'Restore Forum Reply'), ('hide_message', 'Hide Message'), ('restore_message', 'Restore Message'), ('flag_transaction', 'Flag Transaction'), ('unflag_transaction', 'Unflag Transaction'), ('admin_cancel_transaction', 'Admin Cancel Transaction'), ('add_transaction_note', 'Add Transaction Note')], max_length=40)),
                ('target_model', models.CharField(blank=True, max_length=60)),
                ('target_id', models.PositiveIntegerField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransactionMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_messages', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='marketplace.transaction')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
