# Generated by Django 6.0.2 on 2026-02-26 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0007_moderation_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='product_details',
            field=models.JSONField(blank=True, default=dict, help_text='Category-specific product details (brand, size, material, etc.)'),
        ),
    ]
