# Generated by Django 6.0.2 on 2026-02-26 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0008_listing_product_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Verified email or school verification'),
        ),
    ]
