# Generated by Django 4.2.28 on 2026-02-26 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0009_add_profile_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_offer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='offer_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='offer_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='buyer_completed',
            field=models.BooleanField(default=False, help_text='Buyer confirmed exchange happened'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='seller_completed',
            field=models.BooleanField(default=False, help_text='Seller confirmed exchange happened'),
        ),
    ]
