# Generated by Django 6.0.2 on 2026-02-26 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0010_message_is_offer_message_offer_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='campus',
            field=models.CharField(blank=True, choices=[('manila', 'Manila'), ('dapitan', 'Dapitan'), ('pureza', 'Pureza'), ('public', 'Public')], max_length=20, null=True),
        ),
    ]
