# Generated by Django 6.0.2 on 2026-03-01 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0011_listing_campus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='average_rating',
        ),
        migrations.AddField(
            model_name='profile',
            name='reputation_score',
            field=models.DecimalField(decimal_places=2, default=5.0, help_text='Average reputation score from reviews (1-5 stars)', max_digits=3),
        ),
        migrations.AddField(
            model_name='school',
            name='logo_url',
            field=models.URLField(blank=True, help_text='URL to school logo image (preferably PNG with transparency)', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='review_count',
            field=models.PositiveIntegerField(default=0, help_text='Total number of reviews received'),
        ),
    ]
