# Generated by Django 6.0.2 on 2026-03-01 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0013_add_schools_with_logos'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='total_bought',
            field=models.PositiveIntegerField(default=0, help_text='Number of items purchased'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='total_sold',
            field=models.PositiveIntegerField(default=0, help_text='Number of items sold'),
        ),
    ]
