# Generated by Django 6.0.2 on 2026-03-01 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0015_remove_moderationlog_reason_profilepost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='header_image',
            field=models.ImageField(blank=True, help_text='Cover image for your profile header', null=True, upload_to='profile_headers/'),
        ),
    ]
