# Generated by Django 6.0.2 on 2026-03-01 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0017_add_school_logos'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='year_level',
            field=models.CharField(blank=True, choices=[('grade_11', 'Grade 11'), ('grade_12', 'Grade 12'), ('year_1', 'Year 1 - College'), ('year_2', 'Year 2 - College'), ('year_3', 'Year 3 - College'), ('year_4', 'Year 4 - College'), ('year_5', 'Year 5 - College'), ('masters', "Master's Degree"), ('doctorate', 'Doctorate Degree')], help_text='Academic year level', max_length=20, null=True),
        ),
    ]
