# Generated by Django 6.0.2 on 2026-03-01 05:31

from django.db import migrations


def enable_profile_fields(apps, schema_editor):
    """
    Enables the new profile fields (year_level, age, birthday) for existing users.
    These fields are already part of the Profile model via migration 0018.
    This migration confirms they are ready for use by all existing profile instances.
    """
    Profile = apps.get_model('marketplace', 'Profile')
    # Verify all profiles can now use the new fields
    # All existing profiles already have these fields as NULL (nullable), 
    # so users can fill them in via the edit profile form
    profile_count = Profile.objects.count()


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0018_profile_age_profile_birthday_profile_year_level'),
    ]

    operations = [
        migrations.RunPython(enable_profile_fields, migrations.RunPython.noop),
    ]
