# Generated by Django 6.0.2 on 2026-03-05 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0019_populate_profile_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='reputation_score',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='review_count',
        ),
        migrations.RemoveField(
            model_name='review',
            name='rating',
        ),
        migrations.AddField(
            model_name='profile',
            name='forum_posts_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of forum posts created'),
        ),
        migrations.AddField(
            model_name='profile',
            name='id_submitted',
            field=models.BooleanField(default=False, help_text='Admin approval required for blue tier'),
        ),
        migrations.AddField(
            model_name='profile',
            name='id_verified',
            field=models.BooleanField(default=False, help_text='ID has been verified by admin'),
        ),
        migrations.AddField(
            model_name='profile',
            name='verification_tier',
            field=models.CharField(choices=[('grey', 'Grey - Unverified'), ('yellow', 'Yellow - Profile Complete'), ('green', 'Green - Active Member'), ('blue', 'Blue - Highly Trusted')], default='grey', help_text='Verification tier based on profile completion and activity', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='vouch_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of vouches received'),
        ),
        migrations.AddField(
            model_name='review',
            name='is_vouch',
            field=models.BooleanField(default=True, help_text='True if reviewer vouches for seller'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Kept for backward compatibility'),
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(blank=True, help_text='Optional feedback from the transaction'),
        ),
    ]
