# Generated by Django 6.0.2 on 2026-03-05 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0020_update_verification_system'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('twitter', 'Twitter / X'), ('discord', 'Discord'), ('whatsapp', 'WhatsApp'), ('linkedin', 'LinkedIn'), ('viber', 'Viber'), ('telegram', 'Telegram')], max_length=20)),
                ('handle', models.CharField(help_text='Username, handle, or profile URL', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_media', to='marketplace.profile')),
            ],
            options={
                'verbose_name_plural': 'Social Media',
                'ordering': ['platform'],
                'unique_together': {('profile', 'platform')},
            },
        ),
    ]
