# Generated by Django 6.0.2 on 2026-03-05 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0021_socialmedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='listing_type',
            field=models.CharField(choices=[('wts', 'Want to Sell (WTS)'), ('wtb', 'Want to Buy (WTB)')], default='wts', help_text='Specify if you want to sell or buy an item', max_length=10),
        ),
    ]
