# Generated by Django 6.0.2 on 2026-03-06 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0022_listing_listing_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_charge_id', models.CharField(help_text='Stripe charge or payment intent ID', max_length=255, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount paid in PHP', max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('payment_method', models.CharField(default='credit_card', help_text='credit_card, gcash, bank_transfer, in_person', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='marketplace.transaction')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
