# Generated by Django 6.0.2 on 2026-03-06 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0023_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='buyer_confirmed_meeting',
            field=models.BooleanField(default=False, help_text='Buyer confirmed attendance at meeting'),
        ),
    ]
