# Generated by Django 5.2.12 on 2026-03-07 05:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0024_transaction_buyer_confirmed_meeting'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profilepost',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional image for your post (max 5MB)', null=True, upload_to='profile_posts/'),
        ),
        migrations.CreateModel(
            name='ProfilePostComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Comment text (max 500 chars)', max_length=500)),
                ('image', models.ImageField(blank=True, help_text='Optional image in comment (max 2MB)', null=True, upload_to='profile_comments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_edited', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_post_comments', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='marketplace.profilepost')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['post', 'created_at'], name='marketplace_post_id_a25ad7_idx')],
            },
        ),
    ]
