# Generated by Django 6.0.2 on 2026-03-07 07:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0025_profilepost_image_profilepostcomment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(help_text='Unique receipt ID (e.g., RCP-2024-001)', max_length=50, unique=True)),
                ('listing_title', models.CharField(help_text='Snapshot of listing title at time of purchase', max_length=200)),
                ('listing_price', models.DecimalField(decimal_places=2, help_text='Snapshot of price at time of purchase', max_digits=10)),
                ('payment_method', models.CharField(help_text='How the item was paid for', max_length=50)),
                ('processing_fee', models.DecimalField(decimal_places=2, default=0, help_text='2% fee for credit card payments', max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Final amount including fees', max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending - Awaiting seller confirmation'), ('confirmed', 'Confirmed - Seller has acknowledged'), ('completed', 'Completed - Transaction finished'), ('failed', 'Failed - Transaction cancelled')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Additional buyer notes or special instructions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, help_text='When buyer confirmed receipt', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When exchange was completed', null=True)),
                ('buyer', models.ForeignKey(help_text='Buyer of the item', on_delete=django.db.models.deletion.CASCADE, related_name='receipts_received', to=settings.AUTH_USER_MODEL)),
                ('payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='marketplace.payment')),
                ('seller', models.ForeignKey(help_text='Seller of the item', on_delete=django.db.models.deletion.CASCADE, related_name='receipts_issued', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='marketplace.transaction')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
