# Generated by Django 6.0.2 on 2026-03-07 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0026_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('credit_card', 'Credit Card'), ('gcash', 'GCash'), ('bank_transfer', 'Bank Transfer'), ('in_person', 'In-Person Cash'), ('other', 'Other Arrangement')], default='credit_card', help_text='Payment method used', max_length=50),
        ),
    ]
