# Generated by Django 6.0.2 on 2026-03-07 08:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0027_alter_payment_payment_method'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('transaction', 'Transaction Update'), ('message', 'New Message'), ('offer', 'Offer'), ('review', 'Review/Vouch'), ('listing', 'Listing Update'), ('system', 'System Alert'), ('forum', 'Forum Reply')], default='system', max_length=20),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_notifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
