# Generated by Django 5.2.12 on 2026-03-25 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('marketplace', '0030_auditlog_loginattempt_security'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('open', 'Open'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20)),
                ('priority', models.PositiveSmallIntegerField(default=0)),
                ('internal_notes', models.TextField(blank=True)),
                ('public_response', models.TextField(blank=True, help_text='Optional response summary visible to the reporter')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('fraud', 'Fraud / Scam'), ('harassment', 'Harassment / Bullying'), ('spam', 'Spam / Advertising'), ('unsafe_meetup', 'Unsafe Meetup'), ('suspicious', 'Suspicious Activity'), ('refund_dispute', 'Refund / Dispute'), ('other', 'Other')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewing', 'Reviewing'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='new', max_length=20)),
                ('priority', models.PositiveSmallIntegerField(default=0, help_text='Higher numbers are higher priority')),
                ('object_id', models.PositiveIntegerField()),
                ('context_url', models.CharField(blank=True, help_text='Where the report was submitted from', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='marketplace_event_t_5bc6a4_idx',
            old_name='marketplace_event_timestamp_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='marketplace_user_id_a92f2d_idx',
            old_name='marketplace_user_timestamp_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='marketplace_severit_d8dd0d_idx',
            old_name='marketplace_severity_timestamp_idx',
        ),
        migrations.RenameIndex(
            model_name='loginattempt',
            new_name='marketplace_user_id_6d9d9a_idx',
            old_name='marketplace_user_attempt_idx',
        ),
        migrations.AddField(
            model_name='supportticket',
            name='assigned_to',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_support_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userreport',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='userreport',
            name='reported_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userreport',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_submitted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userreport',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_resolved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='report',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to='marketplace.userreport'),
        ),
        migrations.AddIndex(
            model_name='userreport',
            index=models.Index(fields=['status', 'created_at'], name='marketplace_status_65b250_idx'),
        ),
        migrations.AddIndex(
            model_name='userreport',
            index=models.Index(fields=['reason', 'created_at'], name='marketplace_reason_25f5bf_idx'),
        ),
        migrations.AddIndex(
            model_name='userreport',
            index=models.Index(fields=['content_type', 'object_id'], name='marketplace_content_21fcf5_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['status', 'priority', 'created_at'], name='marketplace_status_9eceb8_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['assigned_to', 'status'], name='marketplace_assigne_28000d_idx'),
        ),
    ]
