# Generated by Django 5.2.12 on 2026-03-30 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0031_supportticket_userreport_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='reputation_score',
            field=models.IntegerField(default=100, help_text='User reputation score, decreases with offenses'),
        ),
        migrations.AddField(
            model_name='profile',
            name='strikes_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of rule violations/warnings'),
        ),
        migrations.AddField(
            model_name='userreport',
            name='appeal_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userreport',
            name='appeal_status',
            field=models.CharField(choices=[('none', 'No Appeal'), ('pending', 'Appeal Pending'), ('approved', 'Appeal Approved'), ('rejected', 'Appeal Rejected')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='userreport',
            name='appeal_text',
            field=models.TextField(blank=True, help_text='User explanation for appeal'),
        ),
    ]
