# Generated by Django 5.2.12 on 2026-04-01 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0033_emailtwofactorcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtwofactorcode',
            name='purpose',
            field=models.CharField(choices=[('login', 'Login Verification'), ('sensitive_action', 'Sensitive Action Verification')], default='login', max_length=20),
        ),
    ]
