# Generated by Django 5.2.12 on 2026-04-07 18:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0034_alter_emailtwofactorcode_purpose'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='listing',
            name='preferred_payment_methods',
            field=models.JSONField(blank=True, default=list, help_text='Allowed payment methods selected by the lister'),
        ),
        migrations.AddField(
            model_name='listing',
            name='quantity_available',
            field=models.PositiveIntegerField(default=1, help_text='Remaining quantity available for purchase'),
        ),
        migrations.AddField(
            model_name='listing',
            name='quantity_total',
            field=models.PositiveIntegerField(default=1, help_text='Total quantity posted for this listing'),
        ),
        migrations.AddField(
            model_name='message',
            name='offer_quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='transaction',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='transaction',
            name='seller_confirmed_meeting',
            field=models.BooleanField(default=False, help_text='Seller confirmed meetup/agreement before payment'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='review',
            name='is_vouch',
            field=models.BooleanField(default=True, help_text='True if reviewer vouches for the reviewed user'),
        ),
        migrations.AlterField(
            model_name='review',
            name='seller',
            field=models.ForeignKey(help_text='User being reviewed', on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='review',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='marketplace.transaction'),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('reviewer', 'seller', 'transaction')},
        ),
        migrations.CreateModel(
            name='SchoolIDVerificationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_image', models.ImageField(upload_to='school_ids/')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('reviewer_notes', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_id_requests', to='marketplace.profile')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_school_id_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
