# Generated by Django 5.2.12 on 2026-04-07 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0035_alter_review_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='proposed_meetup_datetime',
            field=models.DateTimeField(blank=True, help_text='Proposed meetup date and time', null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='proposed_meetup_location',
            field=models.CharField(blank=True, choices=[('ust_q_pavilion', 'UST Q-Pavilion (Espana)'), ('ust_dapitan_gate', 'UST Dapitan Gate'), ('ust_p_noval_gate', 'UST P. Noval Gate'), ('feu_gate4_morayta', 'FEU Gate 4 (Morayta)'), ('feu_grandstand', 'FEU Grandstand / Freedom Square'), ('ue_lualhati_sq', 'UE Lualhati Square'), ('nu_main_lobby', 'NU Main Lobby'), ('lrt2_legarda', 'LRT-2 Legarda Station Concourse'), ('lrt2_recto', 'LRT-2 Recto Station Concourse'), ('sm_san_lazaro', 'SM San Lazaro Main Entrance'), ('isetann_recto', 'Isetann Recto Main Entrance'), ('manila', 'General U-Belt Area (Legacy)'), ('dapitan', 'Dapitan Area (Legacy)'), ('pureza', 'Pureza Area (Legacy)'), ('public', 'Public Place (Legacy)')], help_text='Proposed safe meetup location for this deal', max_length=40),
        ),
        migrations.AlterField(
            model_name='listing',
            name='campus',
            field=models.CharField(blank=True, choices=[('ust_q_pavilion', 'UST Q-Pavilion (Espana)'), ('ust_dapitan_gate', 'UST Dapitan Gate'), ('ust_p_noval_gate', 'UST P. Noval Gate'), ('feu_gate4_morayta', 'FEU Gate 4 (Morayta)'), ('feu_grandstand', 'FEU Grandstand / Freedom Square'), ('ue_lualhati_sq', 'UE Lualhati Square'), ('nu_main_lobby', 'NU Main Lobby'), ('lrt2_legarda', 'LRT-2 Legarda Station Concourse'), ('lrt2_recto', 'LRT-2 Recto Station Concourse'), ('sm_san_lazaro', 'SM San Lazaro Main Entrance'), ('isetann_recto', 'Isetann Recto Main Entrance'), ('manila', 'General U-Belt Area (Legacy)'), ('dapitan', 'Dapitan Area (Legacy)'), ('pureza', 'Pureza Area (Legacy)'), ('public', 'Public Place (Legacy)')], help_text='Preferred safe public meetup point in U-Belt', max_length=20, null=True),
        ),
    ]
