# Generated by Django 5.2.12 on 2026-04-13 04:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0037_alter_listing_campus_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='manual_evidence_hash',
            field=models.CharField(blank=True, help_text='SHA-256 hash of submitted verification evidence details', max_length=64),
        ),
        migrations.AddField(
            model_name='payment',
            name='manual_evidence_notes',
            field=models.TextField(blank=True, help_text='Verification notes documenting how manual payment receipt was verified'),
        ),
        migrations.AddField(
            model_name='payment',
            name='manual_evidence_reference',
            field=models.CharField(blank=True, help_text='Reference code or identifier supplied during manual verification', max_length=255),
        ),
        migrations.AddField(
            model_name='payment',
            name='manual_evidence_type',
            field=models.CharField(blank=True, choices=[('gcash_reference', 'GCash reference code'), ('bank_reference', 'Bank transfer reference'), ('cash_receipt', 'Cash receipt or meetup proof'), ('chat_confirmation', 'Chat confirmation evidence'), ('other', 'Other evidence')], help_text='Type of supporting evidence used for manual payment verification', max_length=30),
        ),
        migrations.AddField(
            model_name='payment',
            name='manual_verification_status',
            field=models.CharField(choices=[('not_required', 'Not Required'), ('submitted', 'Submitted by buyer'), ('seller_acknowledged', 'Seller acknowledged submission'), ('verified', 'Verified with evidence'), ('rejected', 'Rejected')], default='not_required', help_text='Verification state for off-platform/manual payment methods', max_length=30),
        ),
        migrations.AddField(
            model_name='payment',
            name='seller_acknowledged_at',
            field=models.DateTimeField(blank=True, help_text='When seller acknowledged a manual payment submission', null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='seller_acknowledged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_manual_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='verified_at',
            field=models.DateTimeField(blank=True, help_text='When payment was verified with evidence and marked completed', null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_manual_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='moderationlog',
            name='action',
            field=models.CharField(choices=[('hide_forum_post', 'Hide Forum Post'), ('restore_forum_post', 'Restore Forum Post'), ('hide_forum_reply', 'Hide Forum Reply'), ('restore_forum_reply', 'Restore Forum Reply'), ('hide_message', 'Hide Message'), ('restore_message', 'Restore Message'), ('flag_transaction', 'Flag Transaction'), ('unflag_transaction', 'Unflag Transaction'), ('admin_cancel_transaction', 'Admin Cancel Transaction'), ('add_transaction_note', 'Add Transaction Note'), ('approve_school_id', 'Approve School ID'), ('reject_school_id', 'Reject School ID')], max_length=40),
        ),
        migrations.CreateModel(
            name='StateTransitionAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('payment', 'Payment'), ('transaction', 'Transaction')], max_length=20)),
                ('transition_kind', models.CharField(choices=[('payment_status', 'Payment Status'), ('manual_verification', 'Manual Verification Status'), ('participant_completion', 'Participant Completion Flag'), ('transaction_status', 'Transaction Status')], max_length=30)),
                ('from_state', models.CharField(blank=True, max_length=40)),
                ('to_state', models.CharField(max_length=40)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('evidence_hash', models.CharField(blank=True, max_length=64)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='state_transition_actions', to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='state_transition_logs', to='marketplace.payment')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_transition_logs', to='marketplace.transaction')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['entity_type', 'created_at'], name='marketplace_entity__92536c_idx'), models.Index(fields=['transition_kind', 'created_at'], name='marketplace_transit_df08f3_idx'), models.Index(fields=['transaction', 'created_at'], name='marketplace_transac_0cc58b_idx'), models.Index(fields=['payment', 'created_at'], name='marketplace_payment_393ae4_idx')],
            },
        ),
    ]
