# Generated by Django 5.2.12 on 2026-04-13 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0038_payment_manual_evidence_hash_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderationlog',
            name='action',
            field=models.CharField(choices=[('hide_forum_post', 'Hide Forum Post'), ('restore_forum_post', 'Restore Forum Post'), ('hide_forum_reply', 'Hide Forum Reply'), ('restore_forum_reply', 'Restore Forum Reply'), ('hide_message', 'Hide Message'), ('restore_message', 'Restore Message'), ('flag_transaction', 'Flag Transaction'), ('unflag_transaction', 'Unflag Transaction'), ('admin_cancel_transaction', 'Admin Cancel Transaction'), ('add_transaction_note', 'Add Transaction Note'), ('approve_manual_payment', 'Approve Manual Payment'), ('reject_manual_payment', 'Reject Manual Payment'), ('approve_school_id', 'Approve School ID'), ('reject_school_id', 'Reject School ID')], max_length=40),
        ),
        migrations.AlterField(
            model_name='payment',
            name='manual_verification_status',
            field=models.CharField(choices=[('not_required', 'Not Required'), ('submitted', 'Submitted by buyer'), ('seller_acknowledged', 'Seller acknowledged submission'), ('awaiting_moderator_review', 'Awaiting moderator review'), ('verified', 'Verified with evidence'), ('rejected', 'Rejected')], default='not_required', help_text='Verification state for off-platform/manual payment methods', max_length=30),
        ),
    ]
