# Generated by Django 5.2.12 on 2026-04-13 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0039_alter_moderationlog_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='buyer_meetup_photo',
            field=models.ImageField(blank=True, help_text='Buyer meetup photo proof for in-person cash transactions', null=True, upload_to='payment_meetup_proofs/'),
        ),
        migrations.AddField(
            model_name='payment',
            name='buyer_meetup_photo_uploaded_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when buyer uploaded meetup photo proof', null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='seller_meetup_photo',
            field=models.ImageField(blank=True, help_text='Seller meetup photo proof for in-person cash transactions', null=True, upload_to='payment_meetup_proofs/'),
        ),
        migrations.AddField(
            model_name='payment',
            name='seller_meetup_photo_uploaded_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when seller uploaded meetup photo proof', null=True),
        ),
    ]
