# Generated by Django 5.2.12 on 2026-04-13 06:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0040_payment_buyer_meetup_photo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='buyer_tracking_acknowledged_at',
            field=models.DateTimeField(blank=True, help_text='When buyer acknowledged receiving the delivery tracking link', null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='seller_tracking_acknowledged_at',
            field=models.DateTimeField(blank=True, help_text='When seller acknowledged receiving the delivery tracking link', null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='third_party_provider',
            field=models.CharField(blank=True, choices=[('lalamove', 'Lalamove'), ('grab', 'Grab'), ('other', 'Other Provider')], help_text='Courier provider used for third-party delivery exchanges', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='third_party_tracking_link',
            field=models.URLField(blank=True, help_text='Shared live tracking/GPS link for the delivery route', max_length=500),
        ),
        migrations.AddField(
            model_name='payment',
            name='third_party_tracking_link_submitted_at',
            field=models.DateTimeField(blank=True, help_text='When the shared delivery tracking link was submitted', null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='third_party_tracking_link_submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_delivery_tracking_links', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payment',
            name='manual_evidence_type',
            field=models.CharField(blank=True, choices=[('gcash_reference', 'GCash reference code'), ('bank_reference', 'Bank transfer reference'), ('cash_receipt', 'Cash receipt or meetup proof'), ('delivery_tracking', 'Delivery tracking proof'), ('chat_confirmation', 'Chat confirmation evidence'), ('other', 'Other evidence')], help_text='Type of supporting evidence used for manual payment verification', max_length=30),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('credit_card', 'Credit Card'), ('gcash', 'GCash'), ('bank_transfer', 'Bank Transfer'), ('in_person', 'In-Person Cash'), ('third_party_delivery', 'Third-Party Delivery (Lalamove/Grab)'), ('other', 'Other Arrangement')], default='credit_card', help_text='Payment method used', max_length=50),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='exchange_method',
            field=models.CharField(choices=[('in_person', 'Meet in Person'), ('gcash', 'GCash (or similar e-wallet)'), ('bank_transfer', 'Bank Transfer'), ('third_party_delivery', 'Third-Party Delivery (Lalamove/Grab)'), ('other', 'Other arrangement')], default='in_person', max_length=20),
        ),
    ]
