# Generated by Django 5.2.12 on 2026-04-15 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0050_transaction_arrival_confirmation'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='pickup_address',
            field=models.TextField(blank=True, help_text='Pickup address to provide to delivery service if third-party delivery is selected'),
        ),
        migrations.AddField(
            model_name='listing',
            name='preferred_third_party_apps',
            field=models.JSONField(blank=True, default=list, help_text='List of preferred third-party delivery apps (e.g., ["lalamove", "grab"])'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='proposed_third_party_app',
            field=models.CharField(blank=True, choices=[], help_text='Buyer proposed third-party delivery app (lalamove or grab)', max_length=20, null=True),
        ),
    ]
