# Generated by Django 5.2.12 on 2026-04-16 01:00
# Removes third-party delivery feature and adds no-show protection system

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0051_listing_pickup_address_and_more'),
    ]

    operations = [
        # Remove third-party delivery fields from Listing
        migrations.RemoveField(
            model_name='listing',
            name='preferred_third_party_apps',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='pickup_address',
        ),
        # Remove third-party delivery field from Transaction
        migrations.RemoveField(
            model_name='transaction',
            name='proposed_third_party_app',
        ),
        # Add no-show protection fields to Transaction
        migrations.AddField(
            model_name='transaction',
            name='no_show_status',
            field=models.CharField(
                choices=[('pending', 'No Issues'), ('reported', 'No-Show Reported'), ('voided', 'Transaction Voided'), ('admin_review', 'Admin Review')],
                default='pending',
                help_text='Status for no-show incidents',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='transaction',
            name='no_show_reported_at',
            field=models.DateTimeField(blank=True, help_text='When no-show was reported', null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='no_show_reported_by',
            field=models.CharField(
                blank=True,
                choices=[('buyer', 'Buyer'), ('seller', 'Seller')],
                help_text='Who reported the no-show',
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name='transaction',
            name='no_show_reason',
            field=models.TextField(blank=True, help_text='Reason for no-show report'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='no_show_admin_action',
            field=models.TextField(blank=True, help_text='Admin action taken on no-show case'),
        ),
    ]
