from django.urls import path
from . import views

app_name = 'marketplace'

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('listings/', views.listing_list, name='listing_list'),
    path('listings/<int:pk>/', views.listing_detail, name='listing_detail'),
    path('listings/create/', views.listing_create, name='listing_create'),
    path('listings/<int:pk>/edit/', views.listing_edit, name='listing_edit'),
    path('ajax/category-fields/', views.get_category_fields, name='get_category_fields'),
    path('listings/<int:pk>/delete/', views.listing_delete, name='listing_delete'),
    path('listings/<int:pk>/sold/', views.listing_mark_sold, name='listing_mark_sold'),
    path('listings/<int:pk>/buy/', views.initiate_purchase, name='initiate_purchase'),
    path('my-listings/', views.my_listings, name='my_listings'),
    path('favorites/', views.favorites_list, name='favorites'),
    path('recommended/', views.recommended_listings, name='recommended'),
    path('chat/', views.recommendation_chat, name='recommendation_chat'),
    path('api/recommendations/gemini/', views.api_gemini_recommendations, name='api_gemini_recommendations'),
    path('api/chat/', views.api_chat_message, name='api_chat_message'),
    path('listings/<int:pk>/favorite/', views.favorite_toggle, name='favorite_toggle'),
    path('notifications/', views.notifications_list, name='notifications'),
    path('notifications/delete/', views.delete_notifications, name='delete_notifications'),
    path('api/recent-notifications/', views.get_recent_notifications, name='get_recent_notifications'),
    path('messages/', views.inbox, name='inbox'),
    path('messages/<int:pk>/', views.conversation_view, name='conversation'),
    path('messages/<int:pk>/offer/', views.make_offer, name='make_offer'),
    path('messages/offer/<int:pk>/respond/', views.respond_to_offer, name='respond_to_offer'),
    path('listings/<int:pk>/message/', views.message_send, name='message_send'),
    path('transactions/<int:transaction_id>/', views.transaction_detail, name='transaction_detail'),
    path('transactions/<int:transaction_id>/confirm/', views.confirm_transaction, name='confirm_transaction'),
    path('transactions/<int:transaction_id>/confirm-arrival/', views.confirm_arrival, name='confirm_arrival'),
    path('transactions/<int:transaction_id>/report-no-show/', views.report_no_show, name='report_no_show'),
    path('transactions/<int:transaction_id>/complete/', views.complete_transaction, name='complete_transaction'),
    path('transactions/<int:transaction_id>/cancel/', views.cancel_transaction, name='cancel_transaction'),
    # Payment URLs
    path('transactions/<int:transaction_id>/payment/', views.payment_checkout, name='payment_checkout'),
    path('transactions/<int:transaction_id>/payment/confirm-received/', views.confirm_payment_received, name='confirm_payment_received'),
    path('transactions/<int:transaction_id>/payment/finalize/', views.payment_finalize_pending, name='payment_finalize_pending'),
    path('transactions/<int:transaction_id>/payment/gcash/', views.payment_gcash, name='payment_gcash'),
    path('transactions/<int:transaction_id>/payment/bank/', views.payment_bank_transfer, name='payment_bank_transfer'),
    path('transactions/<int:transaction_id>/payment/cash/', views.payment_cash_arrangement, name='payment_cash_arrangement'),
    path('transactions/<int:transaction_id>/payment/third-party-delivery/', views.payment_third_party_delivery, name='payment_third_party_delivery'),
    path('transactions/<int:transaction_id>/payment/other/', views.payment_other_arrangement, name='payment_other_arrangement'),
    path('transactions/<int:transaction_id>/payment/success/', views.payment_success, name='payment_success'),
    path('transactions/<int:transaction_id>/payment/cancel/', views.payment_cancel, name='payment_cancel'),
    path('payments/webhooks/stripe/', views.stripe_webhook, name='stripe_webhook'),
    # Receipt URLs
    path('receipts/', views.receipts_list, name='receipts_list'),
    path('receipts/<int:receipt_id>/', views.receipt_detail, name='receipt_detail'),
    path('forum/', views.forum_index, name='forum'),
    path('forum/new/', views.forum_create_post, name='forum_create'),
    path('forum/<int:pk>/', views.forum_post_detail, name='forum_post'),
    path('register/', views.register, name='register'),
    path('profile/complete/', views.complete_profile, name='complete_profile'),
    path('profile/', views.profile_view, name='profile'),
    path('profile/verification/school-id/submit/', views.submit_school_id_verification, name='submit_school_id_verification'),
    path('user/<str:username>/', views.public_profile_view, name='public_profile'),
    path('user/<str:username>/review/', views.leave_review, name='leave_review'),
    path('profile/post/create/', views.create_profile_post, name='create_profile_post'),
    path('profile/post/<int:pk>/delete/', views.delete_profile_post, name='delete_profile_post'),
    path('profile/post/<int:pk>/pin/', views.pin_profile_post, name='pin_profile_post'),
    path('profile/post/<int:post_id>/comment/', views.create_profile_post_comment, name='create_profile_post_comment'),
    path('profile/comment/<int:comment_id>/delete/', views.delete_profile_post_comment, name='delete_profile_post_comment'),
    # Social Media Management
    path('api/social-media/add/', views.add_social_media, name='add_social_media'),
    path('api/social-media/remove/<str:platform>/', views.remove_social_media, name='remove_social_media'),
    path('api/social-media/get/', views.get_social_media, name='get_social_media'),

    # Reporting
    path('report/<str:target>/<int:pk>/', views.report_create, name='report_create'),
    path('appeal/', views.UserAppealsView.as_view(), name='appeals'),
    path('appeal/<int:pk>/', views.appeal_submit, name='appeal_submit'),
    # Moderation (superuser only)
    path('mod/', views.mod_dashboard, name='mod_dashboard'),
    path('mod/sales/', views.mod_sales_analytics, name='mod_sales'),
    path('mod/forum/', views.mod_forum, name='mod_forum'),
    path('mod/forum/<str:content_type>/<int:pk>/', views.mod_forum_action, name='mod_forum_action'),
    path('mod/chat/', views.mod_chat, name='mod_chat'),
    path('mod/chat/<int:pk>/', views.mod_conversation, name='mod_conversation'),
    path('mod/message/<int:pk>/', views.mod_message_action, name='mod_message_action'),
    path('mod/transactions/', views.mod_transactions, name='mod_transactions'),
    path('mod/transactions/<int:transaction_id>/', views.mod_transaction_detail, name='mod_transaction_detail'),
    path('mod/users/', views.mod_users, name='mod_users'),
    path('mod/log/', views.mod_log, name='mod_log'),
    path('mod/security-tests/', views.mod_security_tests, name='mod_security_tests'),
    path('mod/security-tests/probe/', views.mod_security_probe, name='mod_security_probe'),
]
